exclude: "docs"
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.0.1
  hooks:
  - id: reorder-python-imports
    language_version: python3
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--safe, --quiet, --line-length, "100"]
    language_version: python3
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: trailing-whitespace
    language_version: python3
  - id: end-of-file-fixer
    language_version: python3
  - id: check-yaml
    language_version: python3
  - id: debug-statements
    language_version: python3
  - id: flake8
    language_version: python3
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.942
  hooks:
    - id: mypy
      language_version: python3
      additional_dependencies: ["types-attrs"]
