name: pytest-ibutsu tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  create:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1
      - name: Analysis (git diff)
        if: failure()
        run: git diff

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Test with pytest
        run: pytest -v tests/

  test-without-xdist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e .[dev-without-xdist]
      - name: Test with pytest
        run: pytest -v -k "no-xdist"
