name: pytest-ibutsu tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  create:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Pre Commit Checks
        uses: pre-commit/action@v2.0.3
      - name: Analysis (git diff)
        if: failure()
        run: git diff

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install -e .[dev]
      - name: Test with pytest
        run: |
          pytest -v tests/
